language: python

python:
  - 3.5.2

cache: pip

install:
  - pip install -r requirements.txt

services:
  - postgresql
before_script:
  - source ./.travis.sh
  - psql -c "CREATE DATABASE test_db;" -U postgres
script: 
  - nosetests --with-coverage --cover-package app
after_success:
  - coveralls

