"""empty message

Revision ID: 191b20a10a08
Revises: fedf447ed578
Create Date: 2018-05-02 22:52:34.063994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191b20a10a08'
down_revision = 'fedf447ed578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('user_email', sa.String(length=50), nullable=False))
    op.drop_constraint(u'users_email_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['user_email'])
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(u'users_email_key', 'users', ['email'])
    op.drop_column('users', 'user_email')
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###
