"""empty message

Revision ID: 377cbf223ee8
Revises: 191b20a10a08
Create Date: 2018-05-02 22:58:23.394240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377cbf223ee8'
down_revision = '191b20a10a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'users', ['user_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###
