"""empty message

Revision ID: 522556b926ee
Revises: 09b22991f2fc
Create Date: 2018-05-05 07:34:31.231164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522556b926ee'
down_revision = '09b22991f2fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    # ### end Alembic commands ###
