"""empty message

Revision ID: f87b0b8abd7b
Revises: 377cbf223ee8
Create Date: 2018-05-02 23:07:21.913526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f87b0b8abd7b'
down_revision = '377cbf223ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'orders_user_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(u'orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'meals', type_='foreignkey')
    op.drop_column('meals', 'user_id')
    # ### end Alembic commands ###
